# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.0
jobs:
build:
docker:
- image: circleci/node
working_directory: ~/circleci-demo-schedule
steps:
- checkout
- runs:
name: Run Build Command
command: echo "hello I am building and testing"
deploy:
docker:
- image: circleci/node
working_directory: ~/circleci-demo-schedule
steps:
- checkout
- run:
name: Run Deploy Command
command: echo "hello I am deploying"
workflows:
version: 2
commit-workflow:
jobs:
- build
schedule-workflow:
triggers:
- schedule:
cron: "0 * * * *"
filters:
branches:
only:
- master
    jobs:
      - build
      - deploy
